/**
 * Copyright 2025 The Artinet Project
 * SPDX-License-Identifier: Apache-2.0
 */
import z from "zod/v4";
/**
 * @description Meant to be intentionally obscure runtime identifier,
 * `id`s represent the lowest order object in the derived hierarchy.
 * They're predominantly used for tracing/logging purposes.
 * @example An `AgentInstance` is inherited by an `AgentRequest`,
 * in that scenario the `id` represents the `AgentRequest` and not the `AgentInstance`.
 * @note `id`s are not guaranteed to be unique.
 */
export const BaseSchema = z.object({
  id: z.string(),
});
export type Base = z.infer<typeof BaseSchema>;
//todo: move below to utils
export const CallerIdSchema = z.object({
  callerId: z.string().optional().describe(`
The ID of the caller.
Could be an agent, tool, or other identifier.
`),
}).describe(`
Caller ID Schema: 
Used for tracing and potential post-processing. 
The callerId may represent an entirely different runtime environment.
Is generated by the caller and is not guaranteed to be unique.
`);
export type CallerId = z.infer<typeof CallerIdSchema>;

export const WithKindSchema = z.object({
  kind: z
    .string()
    .describe(
      "The kind of the object. Used for type checking and potential post-processing."
    ),
}).describe(`
With Kind Schema:
Used for type checking and potential post-processing.
The kind may represent an entirely different type of object.
Is generated by the object and is not guaranteed to be accurate.
`);
export type WithKind = z.infer<typeof WithKindSchema>;

const literalSchema = z.union([z.string(), z.number(), z.boolean(), z.null()]);
type Literal = z.infer<typeof literalSchema>;
type JSON = Literal | { [key: string]: JSON } | JSON[];
//todo: convert to zod/v4 JSONSchema
export const JSONSchema: z.ZodType<JSON> = z.lazy(() =>
  z.union([
    literalSchema,
    z.array(JSONSchema),
    z.record(z.string(), JSONSchema),
  ])
);

export const ContextKindSchema = z.enum([
  "agent_request",
  "agent_response",
  "tool_request",
  "tool_response",
]);
export const ContextKind = ContextKindSchema.enum;
export type ContextKind = z.infer<typeof ContextKindSchema>;
